apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-user-service
  name: api-user-svc
spec:
  selector:
    app: udagram-api-user
  ports:
    - name: "2310"
      protocol: TCP
      port: 80
      targetPort: 2310
